clone_depth: 5

environment:
  QTDIR32: C:\Qt\5.7.0\msvc2015
  QTDIR64: C:\Qt\5.7.0
  GENERATOR64: "Visual Studio 14 Win64"
  GENERATOR32: "Visual Studio 14"
  CONFIG: Release

configuration:
  - Release

platform:
  - x64
  - Win32

#branches:
  #only:
    #- master

before_build:
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - cmd: if "%platform%"=="Win32" cmake "-G%GENERATOR32%" -DCMAKE_PREFIX_PATH="%QTDIR32%/lib/cmake/Qt5" ..
  - cmd: if "%platform%"=="x64"   cmake "-G%GENERATOR64%" -DCMAKE_PREFIX_PATH="%QTDIR64%/lib/cmake/Qt5" ..

build:
  parallel: true
  project: C:\projects\plotjuggler\build\PlotJuggler.sln

