sudo: required
dist: trusty

language: generic 
compiler:
  - gcc

os:
  - linux
  
compiler:
  - gcc

env:
  matrix:
    - ROS_DISTRO="indigo" 
    - ROS_DISTRO="kinetic" 

before_install:

 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get -y install -f qtbase5-dev qt5-default libqt5svg5-dev libqt5qml5

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci
  
script:
  - .industrial_ci/travis.sh

notifications:
  email:
    recipients:
      - davide.faconti@gmail.com
    on_success: change
    on_failure: always
